<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>CSS User Profile Card</title>
    <link rel="stylesheet" href="Estatico/Estilos/styles-apuestas.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <style>
        .people-nearby .nearby-user{
        padding: 20px 0;
        border-radius: 8px;
        border-top: 2px solid #f1f2f2;
        border-bottom: 2px solid #f1f2f2;
        border-right: 2px solid #f1f2f2;
        border-left: 2px solid #f1f2f2;
        margin-bottom: 20px;
        background: white;
        }

        img.profile-photo-lg{
        height: 80px;
        width: 80px;
        border-radius: 50%;
        }
    </style>
</head>
<body>
<input type="checkbox" id="check">
    <header>
    
        <div class = "barra_superior">
            <div class = "logo">                
                 <a href="index.php?c=Usuario&&a=apuestas"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>  
                 <label for="check">
                    <i class="fas fa-bars" id="sidebar_btn" style="color:#707d8c;"></i>
                </label>      
            </div>
            <nav class="navegacion">
                <ul>
                    <li>
                        <div class="action" onclick="menuToggle();">
                            <div class="profile">
                                <img src="Estatico/Imagenes/avatar.png"  width="100%" height="100%">
                            </div>
                            <div class="menu">
                                <h3>
                                    <?php
                                         echo $_SESSION['identidad']->identificador;
                                    ?>
                                    <br><span>Diseñador Web</span>
                                </h3>
                                <ul>
                                    <li><img src="Estatico/Imagenes/user.png"><a href="index.php?c=Usuario&&a=miperfil">Mi perfil</a></li>
                                    <li><img src="Estatico/Imagenes/edit.png"><a href="index.php?c=Usuario&&a=editar_usuario">Editar perfil</a></li>
                                    <li><img src="Estatico/Imagenes/envelope.png"><a href="index.php?c=Amistad&&a=bandeja">Bandeja</a></li>
                                    <li><img src="Estatico/Imagenes/log-out.png"><a href="index.php?c=Usuario&&a=logout">Cerrar Sesión</a></li>
                                </ul>
                            </div>
                        </div>
                        <script>
                            function menuToggle(){
                                const toggleMenu = document.querySelector('.menu');
                                toggleMenu.classList.toggle('active');
                            }
                        </script>
                    </li>
                </ul>            
            </nav>
        </div>
    </header>

    <div class="sidebar">
    <center>
            <?php
                $nombre_foto = $_SESSION['identidad']->id;
                $type = '.jpg';
                $nombre_foto = $nombre_foto.$type;                
                echo '<img src="Estatico/Profiles/'.$nombre_foto.'" class="profile_image" alt="">';
            ?>
           
            <h4>
                <?php
                    echo "Hola, ".$_SESSION['identidad']->identificador;
                ?>
            </h4>
        </center>
        <a href="index.php?c=Usuario&&a=apuestas"><i class="fas fa-home" style="color:#707d8c;"></i><span>Inicio</span></a>
        <a href="index.php?c=Usuario&&a=apostar"><i class="far fa-money-bill-alt" style="color:#707d8c;"></i><span>Apostar</span></a>
        <a href="index.php?c=Amistad&&a=amigo"><i class="fas fa-users" style="color:#707d8c;"></i><span>Amigos</span></a>
        <a href="index.php?c=Usuario&&a=aprobadas"><i class="far fa-thumbs-up" style="color:#707d8c;"></i><span>Asig.Aprobadas</span></a>
        <a href="index.php?c=Usuario&&a=matriculadas"><i class="far fa-address-book" style="color:#707d8c;"></i><span>Asig.Matriculadas</span></a>       
    </div>
    
    <div class="contenido">
        <form class="container" action="index.php?c=Usuario&&a=apostar" method="POST" name="apuestas">
            <select class="form-select" aria-label=".form-select-sm example " name="asignaturas" >
                <option value="false">Seleccione una asignatura para apostar:</option>
                <?php
                    while($asignatura=$misasignaturas->fetchObject()){
                        echo "<option value=".$asignatura->id_asignatura.">".$asignatura->nombre_asignatura."</option>";
                    }
                ?>
            </select>
            <br>
            <select class="form-select" aria-label=".form-select-sm example " name="apuesta" >
                <option value="false">Seleccione una apuesta:</option>
                <?php
                    while($apuesta=$apuestas->fetchObject()){
                        echo "<option value=".$apuesta->id_apuesta.">".$apuesta->cuota." - ".$apuesta->descripcion."</option>";
                    }
                ?>
            </select>
            <br>
            <input type="number" min=1 max=<?= $_SESSION['identidad']->pinfcoins ?> placeholder="<?php echo '1 - '.$_SESSION['identidad']->pinfcoins; ?>" name='pinfcoin'>
            <input class="btn btn-primary" type="submit" name="apuestas" value="Enviar">
        </form>
        <?php 
        if (isset($aleatorio)) {?>
        <p>Has sacado un: <?= $aleatorio ?></p>
        <?php } ?>

        <br>
        <div class="container">
            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading">¡Ya puedes apostar!</h4>
                <p>Apuesta aquellas asignaturas que piensas que vas a aprobar o suspender, pero... ¡CIUDADO! No vaya a ser que 
                    te quedes sin PINFcoins. Recuerda apostar con sabiduría. Estudiantes... ¡APUESTEN!
                </p>
                <hr>
                <p class="mb-0">Los PINFcoins se generan una vez hayas aprobado la asignatura, no te desanimes si los pierdes todos :)</p>
            </div>
        </div>
    </div>

</body>
</html>