<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="Estatico/Estilos/styles-apuestas.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

    <title>Document</title>
</head>
<body>
    <input type="checkbox" id="check">
    <header>
    
        <div class = "barra_superior">
            <div class = "logo">                
                 <a href="index.php?c=Usuario&&a=apuestas"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>  
                 <label for="check">
                    <i class="fas fa-bars" id="sidebar_btn" style="color:#707d8c;"></i>
                </label>      
            </div>
            <nav class="navegacion">
                <ul>
                    <li>
                        <div class="action" onclick="menuToggle();">
                            <div class="profile">
                                <img src="Estatico/Imagenes/avatar.png"  width="100%" height="100%">
                            </div>
                            <div class="menu">
                                <h3>
                                    <?php
                                         echo $_SESSION['identidad']->identificador;
                                    ?>
                                    <br><span>Estudiante</span>
                                </h3>
                                <ul>
                                    <li><img src="Estatico/Imagenes/user.png"><a href="index.php?c=Usuario&&a=miperfil">Mi perfil</a></li>
                                    <li><img src="Estatico/Imagenes/edit.png"><a href="index.php?c=Usuario&&a=editar_usuario">Editar perfil</a></li>
                                    <li><img src="Estatico/Imagenes/envelope.png"><a href="index.php?c=Amistad&&a=bandeja">Bandeja</a></li>
                                    <li><img src="Estatico/Imagenes/log-out.png"><a href="index.php?c=Usuario&&a=logout">Cerrar Sesión</a></li>
                                </ul>
                            </div>
                        </div>
                        <script>
                            function menuToggle(){
                                const toggleMenu = document.querySelector('.menu');
                                toggleMenu.classList.toggle('active');
                            }
                        </script>
                    </li>
                </ul>            
            </nav>
        </div>
    </header>

    <div class="sidebar">
    <center>
            <?php
                $nombre_foto = $_SESSION['identidad']->id;
                $type = '.jpg';
                $nombre_foto = $nombre_foto.$type;
                echo '<img src="Estatico/Profiles/'.$nombre_foto.'" class="profile_image" alt="">';
            ?>

            <h4>
                <?php
                    echo "".$_SESSION['identidad']->identificador;
                ?>
            </h4>
    </center>
        <a href="index.php?c=Usuario&&a=apuestas"><i class="fas fa-home" style="color:#707d8c;"></i><span>Inicio</span></a>
        <a href="index.php?c=Usuario&&a=apostar"><i class="far fa-money-bill-alt" style="color:#707d8c;"></i><span>Apostar</span></a>
        <a href="index.php?c=Amistad&&a=amigo"><i class="fas fa-users" style="color:#707d8c;"></i><span>Amigos</span></a>
        <a href="index.php?c=Usuario&&a=aprobadas"><i class="far fa-thumbs-up" style="color:#707d8c;"></i><span>Asig.Aprobadas</span></a>
        <a href="index.php?c=Usuario&&a=matriculadas"><i class="far fa-address-book" style="color:#707d8c;"></i><span>Asig.Matriculadas</span></a>
    </div>

    <i class="fas fa-home"></i>

    <div class="contenido">
        <form class="container" action="index.php?c=Usuario&&a=aprobadas" method="POST" name="aprobadas">
            <select class="form-select" aria-label=".form-select-sm example " name="asignaturas" >
                <option value="false">Seleccione una asignatura aprobada:</option>
                <?php
                    while($asignatura=$asignaturas->fetchObject()){
                        echo "<option value=".$asignatura->id_asignatura.">".$asignatura->nombre_asignatura."</option>";
                    }
                ?>
            </select>
            <br>
            <input type="text" id="notas" name="notas" required minlength="1" maxlength="2" size="10">
            <input class="btn btn-primary" type="submit" name="aprobadas" value="Enviar">
            <br></br>
            <?php if(isset($_SESSION['error_asignatura_aprobada']) && $_SESSION['error_asignatura_aprobada']){
                echo "<p class='alert alert-danger'>".$_SESSION['error_asignatura_aprobada']."</p>";
            }?>
        </form>
        <br>
        <div class="container">
            <div class="alert alert-warning" role="alert">
            Recuerda que al aprobar una asignatura cumples con los términos y condiciones de la aplicación.
            <br>
            Está totalmente prohibido añadir asignaturas aprobadas sin haberlas aprobado. Supondrá una suspensión de la cuenta
            </div>  
        </div>

    </div>
  

</body>
</html>