<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="Estatico/Estilos/styles-apuestas.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
</head>
<body>
    <input type="checkbox" id="check">
    <header>
        <div class = "barra_superior">

            <div class = "logo">                
                 <a href="index.php"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>   
                 <label for="check">
                    <i class="fas fa-bars" id="sidebar_btn"></i>
                </label>      
            </div>
            <nav class="navegacion">
                <ul>
                    <li><a href= "index.php?c=Usuario&&a=logout">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        Cerrar Sesión
                        </a>
                    </li>
                </ul>            
            </nav>
        </div>
    </header>

    <div class="sidebar">
        <center>
            <img src="Estatico/Imagenes/antonio.jpg" class="profile_image" alt="">
            <h4>
                <?php
                    echo "Hola, ".$_SESSION['identidad']->identificador;
                ?>
            </h4>
        </center>
        <a href="#"><i class="far fa-money-bill-alt"></i><span>Apostar</span></a>
        <a href="#"><i class="fas fa-users"></i><span>Amigos</span></a>
        <a href="#"><i class="fas fa-info-circle"></i><span>Ayuda</span></a>
        <a href="#"><i class="fas fa-shield-alt"></i><span>Opciones</span></a>        
    </div>


    <div class="contenido">

    </div>
</body>
</html>