<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="Estatico/Estilos/styles-apuestas.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- cookiealert.css -->
    <link rel="stylesheet" href="Estatico/Estilos/cookiealert.css">
</head>
<body>
    <input type="checkbox" id="check">
    <header>
    
        <div class = "barra_superior">
            <div class = "logo">                
                 <a href="index.php?c=Usuario&&a=apuestas"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>  
                 <label for="check">
                    <i class="fas fa-bars" id="sidebar_btn" style="color:#707d8c;"></i>
                </label>      
            </div>
            <nav class="navegacion">
                <ul>
                    <li>
                        <div class="action" onclick="menuToggle();">
                            <div class="profile">
                                <img src="Estatico/Imagenes/avatar.png"  width="100%" height="100%">
                            </div>
                            <div class="menu">
                                <h3>
                                    <?php
                                         echo $_SESSION['identidad']->identificador;
                                    ?>
                                    <br><span>Diseñador Web</span>
                                </h3>
                                <ul>
                                    <li><img src="Estatico/Imagenes/user.png"><a href="#">Mi perfil</a></li>
                                    <li><img src="Estatico/Imagenes/edit.png"><a href="index.php?c=Usuario&&a=editar_usuario">Editar perfil</a></li>
                                    <li><img src="Estatico/Imagenes/envelope.png"><a href="#">Bandeja</a></li>
                                    <li><img src="Estatico/Imagenes/settings.png"><a href="#">Ajustes</a></li>
                                    <li><img src="Estatico/Imagenes/question.png"><a href="#">Ayuda</a></li>
                                    <li><img src="Estatico/Imagenes/log-out.png"><a href="index.php?c=Usuario&&a=logout">Cerrar Sesión</a></li>
                                </ul>
                            </div>
                        </div>
                        <script>
                            function menuToggle(){
                                const toggleMenu = document.querySelector('.menu');
                                toggleMenu.classList.toggle('active');
                            }
                        </script>
                    </li>
                </ul>            
            </nav>
        </div>
    </header>

    <div class="sidebar">
        <center>
            <img src="Estatico/Imagenes/antonio.jpg" class="profile_image" alt="">
            <h4>
                <?php
                    echo "Hola, ".$_SESSION['identidad']->identificador;
                ?>
            </h4>
        </center>
        <a href="#"><i class="far fa-money-bill-alt" style="color:#707d8c;"></i><span>Apostar</span></a>
        <a href="#"><i class="fas fa-users" style="color:#707d8c;"></i><span>Amigos</span></a>
        <a href="#"><i class="fas fa-info-circle" style="color:#707d8c;"></i><span>Ayuda</span></a>
        <a href="#"><i class="fas fa-shield-alt" style="color:#707d8c;"></i><span>Opciones</span></a>        
    </div>
    
    <div class="contenido">
        
        <div class="container">
            <div class = "row">
                <div class="col">
                    <div class="alert alert-success alert-dissmisable">
                        has iniciado sesión correctamente
                        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                    </div>                      
                </div>
            </div>
        
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="Estatico/Imagenes/slider1" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="Estatico/Imagenes/slider2" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="Estatico/Imagenes/slider3.png" class="d-block w-100" alt="...">
                </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
                </a>
            </div>       

        <div class="lot-of-cards">
                    <div class="card">
                        <div class="imgBx">
                            <img src="Estatico/Imagenes/pinfcoin.png">
                        </div>
                        <div class="contentBx">
                            <h3>Quiero Pinfcoins</h3>
                            <h2 class="price">Comience ahora a apostar</h2>
                            <a href="#" class="apostar">Apueste!!</a>
                        </div>
                    </div>    
                    <div class="card2">
                        <div class="imgBx">
                            <img src="Estatico/Imagenes/vector.png">
                        </div>
                        <div class="contentBx">
                            <h3>Asignaturas</h3>
                            <h2 class="price">¡He aprobado una asignatura!</h2>
                            <a href="#" class="apostar">Agregala!!</a>
                        </div>
                    </div>    
                    <div class="card3">
                        <div class="imgBx">
                            <img src="Estatico/Imagenes/amigotes.png">
                        </div>
                        <div class="contentBx">
                            <h3>Amigos</h3>
                            <h2 class="price">¡Agregue a tus amigos!</h2>
                            <a href="#" class="apostar">Añadelos!!</a>
                        </div>
                    </div> 
            </div> 
        </div>        
    </div>       
    <div class="alert alert-dismissible text-center cookiealert" role="alert">
        <div class="cookiealert-container">
      <b>Do you like cookies?</b> &#x1F36A; We use cookies to ensure you get the best experience on our website. <a href="http://cookiesandyou.com/" target="_blank">Learn more</a>

      <button type="button" class="btn btn-primary btn-sm acceptcookies" aria-label="Close">
          I agree
      </button>
        </div>
    </div>
    <script src="Scripts/cookiealert.js"></script>    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>