<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="Estatico/Estilos/asignaturas.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

    <title>Document</title>
</head>
<body>
    <input type="checkbox" id="check">
    <header>
    
        <div class = "barra_superior">
            <div class = "logo">                
                 <a href="index.php?c=Usuario&&a=apuestas"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>  
                 <label for="check">
                    <i class="fas fa-bars" id="sidebar_btn" style="color:#707d8c;"></i>
                </label>      
            </div>
            <nav class="navegacion">
                <ul>
                    <li>
                        <div class="action" onclick="menuToggle();">
                            <div class="profile">
                                <img src="Estatico/Imagenes/avatar.png"  width="100%" height="100%">
                            </div>
                            <div class="menu">
                                <h3>
                                    <?php
                                         echo $_SESSION['identidad']->identificador;
                                    ?>
                                    <br><span>Estudiante</span>
                                </h3>
                                <ul>
                                    <li><img src="Estatico/Imagenes/user.png"><a href="index.php?c=Usuario&&a=miperfil">Mi perfil</a></li>
                                    <li><img src="Estatico/Imagenes/edit.png"><a href="index.php?c=Usuario&&a=editar_usuario">Editar perfil</a></li>
                                    <li><img src="Estatico/Imagenes/envelope.png"><a href="#">Bandeja</a></li>
                                    <li><img src="Estatico/Imagenes/settings.png"><a href="#">Ajustes</a></li>
                                    <li><img src="Estatico/Imagenes/question.png"><a href="#">Ayuda</a></li>
                                    <li><img src="Estatico/Imagenes/log-out.png"><a href="index.php?c=Usuario&&a=logout">Cerrar Sesión</a></li>
                                </ul>
                            </div>
                        </div>
                        <script>
                            function menuToggle(){
                                const toggleMenu = document.querySelector('.menu');
                                toggleMenu.classList.toggle('active');
                            }
                        </script>
                    </li>
                </ul>            
            </nav>
        </div>
    </header>

    <div class="sidebar">
        <center>
            <img src="Estatico/Imagenes/antonio.jpg" class="profile_image" alt="">
            <h4>
                <?php
                    echo "Hola, ".$_SESSION['identidad']->identificador;
                ?>
            </h4>
        </center>
        <a href="index.php?c=Usuario&&a=apuestas"><i class="fas fa-home" style="color:#707d8c;"></i><span>Inicio</span></a>
        <a href="#"><i class="far fa-money-bill-alt" style="color:#707d8c;"></i><span>Apostar</span></a>
        <a href="index.php?c=Usuario&&a=amigos"><i class="fas fa-users" style="color:#707d8c;"></i><span>Amigos</span></a>
        <a href="index.php?c=Usuario&&a=aprobadas"><i class="far fa-thumbs-up" style="color:#707d8c;"></i><span>Asig.Aprobadas</span></a>
        <a href="index.php?c=Usuario&&a=asignaturas"><i class="far fa-address-book" style="color:#707d8c;"></i><span>Asig.Matriculadas</span></a>
            
    </div>

    <i class="fas fa-home"></i>

    <div class="contenido">
        <div class="container">
            <select class="form-select form-select-sm" aria-label=".form-select-sm example">
                <option selected>Seleccione asignatura matriculada</option>
                <option value="1">Analisis de Algoritmos</option>
                <option value="2">Matematica Discreta</option>
                <option value="3">Redes de Computadores</option>
            </select>
            <br>
            <div class="col-12">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="button" class="btn btn-primary">Enviar</button>
                </div>
            </div>
        </div>
    </div>
  

</body>
</html>