<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="Estatico/Estilos/styles-apuestas.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<input type="checkbox" id="check">
<header>
        <div class = "barra_superior">
            <div class = "logo">                
                 <a href="index.php?c=Usuario&&a=apuestas"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>  
                 <label for="check">
                    <i class="fas fa-bars" id="sidebar_btn" style="color:#707d8c;"></i>
                </label>      
            </div>
            <nav class="navegacion">
                <ul>
                    <li>
                        <div class="action" onclick="menuToggle();">
                            <div class="profile">
                                <img src="Estatico/Imagenes/avatar.png"  width="100%" height="100%">
                            </div>
                            <div class="menu">
                                <h3>
                                    <?php
                                         echo $_SESSION['identidad']->identificador;
                                    ?>
                                    <br><span>Diseñador Web</span>
                                </h3>
                                <ul>
                                    <li><img src="Estatico/Imagenes/user.png"><a href="index.php?c=Usuario&&a=miperfil">Mi perfil</a></li>
                                    <li><img src="Estatico/Imagenes/edit.png"><a href="index.php?c=Usuario&&a=editar_usuario">Editar perfil</a></li>
                                    <li><img src="Estatico/Imagenes/envelope.png"><a href="#">Bandeja</a></li>
                                    <li><img src="Estatico/Imagenes/settings.png"><a href="#">Ajustes</a></li>
                                    <li><img src="Estatico/Imagenes/question.png"><a href="#">Ayuda</a></li>
                                    <li><img src="Estatico/Imagenes/log-out.png"><a href="index.php?c=Usuario&&a=logout">Cerrar Sesión</a></li>
                                </ul>
                            </div>
                        </div>
                        <script>
                            function menuToggle(){
                                const toggleMenu = document.querySelector('.menu');
                                toggleMenu.classList.toggle('active');
                            }
                        </script>
                    </li>
                </ul>            
            </nav>
        </div>
    </header>

    <div class="sidebar">
        <center>
            <img src="Estatico/Imagenes/antonio.jpg" class="profile_image" alt="">
            <h4>
                <?php
                    echo "Hola, ".$_SESSION['identidad']->identificador;
                ?>
            </h4>
        </center>
        <a href="index.php?c=Usuario&&a=apuestas"><i class="fas fa-home" style="color:#707d8c;"></i><span>Inicio</span></a>
        <a href="#"><i class="far fa-money-bill-alt" style="color:#707d8c;"></i><span>Apostar</span></a>
        <a href="#"><i class="fas fa-users" style="color:#707d8c;"></i><span>Amigos</span></a>
        <a href="index.php?c=Usuario&&a=aprobadas"><i class="far fa-thumbs-up" style="color:#707d8c;"></i><span>Asig.Aprobadas</span></a>
        <a href="index.php?c=Usuario&&a=asignaturas"><i class="far fa-address-book" style="color:#707d8c;"></i><span>Asig.Matriculadas</span></a>
        <a href="#"><i class="fas fa-shield-alt" style="color:#707d8c;"></i><span>Opciones</span></a>     
    </div>
<body>
  <div class= "contenido">
    <div class="container">
      <!-- Main content -->  
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <div class="col-md-8">         
          <!-- /.box -->
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-headerwith-border">
              <h3 class="box-title">Editar mi perfil</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="POST" name="edit_user" action="index.php?c=Usuario&&a=editar_usuario" enctype="multipart/form-data">
              <div class="box-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Nombre </label>
                    <input type="text" name="nombres" class="form-control" placeholder="Nombre" value="<?php echo $_SESSION['identidad']->Nombre;?>">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1">Apellidos </label>
                    <input type="text" name="apellidos" class="form-control" placeholder="Apellidos" value="<?php echo $_SESSION['identidad']->Apellidos;?>">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1">Usuario</label>
                    <input type="text" name="identificadores" class="form-control" placeholder="Usuario" value="<?php echo $_SESSION['identidad']->identificador;?>">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1">Email</label>
                    <input type="email" name="correos" class="form-control" placeholder="Email" value="<?php echo $_SESSION['identidad']->email;?>">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1">Contraseña</label>
                    <input type="password" name="contrasenas" class="form-control" placeholder="Contraseña" value="<?php echo $_SESSION['identidad']->contrasena;?>">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1">Carrera</label>
                    <select class="form-control" name="carreras" id="carreras">
                      <option value="<?php echo $_SESSION['identidad']->id_carrera;?>">Mantener actual</option>
                      <?php
                          while($carrera=$carreras->fetchObject()){
                            echo "<option value=".$carrera->id_carrera.">".$carrera->nombre_carrera."</option>";
                          }
                      ?>
                    </select>
                  </div>

                </div><!-- /.box-body -->

                <div class="box-footer">
                  <button type="submit" name="edit_user" class="btn btn-primary">Actualizar datos</button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>