<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<div class="content-wrapper">

<!-- Main content -->
<section class="content">

  
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <div class="col-md-8">
      <!-- /.box -->



      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Editar mi perfil</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="POST" action="index.php?c=Usuario&&a=editar_usuario" enctype="multipart/form-data">
          <div class="box-body">
            <div class="form-group">
              <label for="exampleInputEmail1">Nombre </label>
              <input type="text" name="nombres" class="form-control" placeholder="Nombre" value="<?php echo $_SESSION['identidad']->nombre;?>">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Apellidos </label>
              <input type="text" name="apellidos" class="form-control" placeholder="Apellidos" value="<?php echo $_SESSION['identidad']->apellidos;?>">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Usuario</label>
              <input type="text" name="identificadores" class="form-control" placeholder="Usuario" value="<?php echo $_SESSION['identidad']->identificador;?>">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Email</label>
              <input type="email" name="correos" class="form-control" placeholder="Email" value="<?php echo $_SESSION['identidad']->email;?>">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Contraseña</label>
              <input type="password" name="contrasenas" class="form-control" placeholder="Email" value="<?php $_SESSION['identidad']->contrasena;?>">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Carrera</label>
              <select class="form-control" name="carreras" id="carreras" value="<?php $_SESSION['identidad']->carrera;?>" >
                <option value="false">Seleccione una carrera:</option>
                <option value="GII">Ingeniería Informática</option>
                <option value="GIA">Ingeniería Aeroespacial</option>
                <option value="GIM">Ingeniería Mecánica</option>
            </select>
            </div>
            

          <!-- /.box-body -->

          <div class="box-footer">
            <button type="submit" name="actualizar" class="btn btn-primary">Actualizar datos</button>
          </div>
        </form>
      </div>
</body>
</html>