<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Pinfbet</title>
        <link rel="stylesheet" href="Estatico/Estilos/estilos.css">
       
    </head>
    <body>
        <header>
            <div class = "barra_superior">
                <div class = "logo">
                     <a href="index.php"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>         
                </div>
                <nav class="navegacion">
                    <ul>
                        <li><a href= "index.php?c=Usuario&&a=contacto">Contacto</a></li>
                        <li><a href= "index.php?c=Usuario&&a=terminos">Condiciones</a></li>
                        <li><a href= "index.php?c=Usuario&&a=ayuda">Ayuda</a></li>
                    </ul>            
                </nav>
            </div>
        </header>
    <form class="login" method="POST" action="index.php?c=Usuario&&a=iniciosesion">
        <h4>Inicia Sesion</h4>
        <input class="controls" type="email" name="correos" id="correos" placeholder="Ingrese su correo"> 
        <input class="controls" type="password" name="contrasenas" id="contrasenas" placeholder="Ingrese su contraseña">
        <?php
            if (isset($_SESSION['error_login']) && $_SESSION['error_login']){
                echo "<p class='error'>".$_SESSION['error_login']."</p>";
            }
        ?>
        <input class="botons" type="submit" name="inicio" value="Iniciar Sesion">
        <p><a href="index.php?c=Usuario&&a=cambiocontra">¿Ha olvidado su contraseña?</a></p>
    </form>
    </body>
</html>