<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>CSS User Profile Card</title>
    <link rel="stylesheet" href="Estatico/Estilos/miperfil.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
<input type="checkbox" id="check">
    <header>
    
        <div class = "barra_superior">
            <div class = "logo">                
                 <a href="index.php?c=Usuario&&a=apuestas"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>  
                 <label for="check">
                    <i class="fas fa-bars" id="sidebar_btn" style="color:#707d8c;"></i>
                </label>      
            </div>
            <nav class="navegacion">
                <ul>
                    <li>
                        <div class="action" onclick="menuToggle();">
                            <div class="profile">
                                <img src="Estatico/Imagenes/avatar.png"  width="100%" height="100%">
                            </div>
                            <div class="menu">
                                <h3>
                                    <?php
                                         echo $_SESSION['identidad']->identificador;
                                    ?>
                                    <br><span>Diseñador Web</span>
                                </h3>
                                <ul>
                                    <li><img src="Estatico/Imagenes/user.png"><a href="index.php?c=Usuario&&a=miperfil">Mi perfil</a></li>
                                    <li><img src="Estatico/Imagenes/edit.png"><a href="index.php?c=Usuario&&a=editar_usuario">Editar perfil</a></li>
                                    <li><img src="Estatico/Imagenes/envelope.png"><a href="#">Bandeja</a></li>
                                    <li><img src="Estatico/Imagenes/settings.png"><a href="#">Ajustes</a></li>
                                    <li><img src="Estatico/Imagenes/question.png"><a href="#">Ayuda</a></li>
                                    <li><img src="Estatico/Imagenes/log-out.png"><a href="index.php?c=Usuario&&a=logout">Cerrar Sesión</a></li>
                                </ul>
                            </div>
                        </div>
                        <script>
                            function menuToggle(){
                                const toggleMenu = document.querySelector('.menu');
                                toggleMenu.classList.toggle('active');
                            }
                        </script>
                    </li>
                </ul>            
            </nav>
        </div>
    </header>

    <div class="sidebar">
        <center>
            <img src="Estatico/Imagenes/antonio.jpg" class="profile_image" alt="">
            <h4>
                <?php
                    echo "Hola, ".$_SESSION['identidad']->identificador;
                ?>
            </h4>
        </center>
        <a href="#"><i class="far fa-money-bill-alt" style="color:#707d8c;"></i><span>Apostar</span></a>
        <a href="#"><i class="fas fa-users" style="color:#707d8c;"></i><span>Amigos</span></a>
        <a href="#"><i class="fas fa-info-circle" style="color:#707d8c;"></i><span>Ayuda</span></a>
        <a href="#"><i class="fas fa-shield-alt" style="color:#707d8c;"></i><span>Opciones</span></a>        
    </div>
<body>
<div class="contenido">
    <div class="wrapper">
        <div class="left">
            <img src="Estatico/Imagenes/s2-minimized.png" 
            alt="user" width="100">
            <h4><?php echo $_SESSION['identidad']->identificador;?></h4>
            <p>Usuario</p>
        </div>
        <div class="right">
            <div class="info">
                <h3>Información Personal</h3>
                <div class="info_data">
                    <div class="data">
                        <h4>Nombre</h4>
                        <p><?php echo $_SESSION['identidad']->Nombre;?></p>
                    </div>
                    <div class="data">
                        <h4>Apellidos</h4>
                        <p><?php echo $_SESSION['identidad']->Apellidos;?></p>
                    </div>
                    
                </div>
            </div>
        
        <div class="projects">
                <h3></h3>
                <div class="projects_data">
                    <div class="data">
                        <h4>Email</h4>
                        <p><?php echo $_SESSION['identidad']->email;?></p>
                    </div>
                    <div class="data">
                    <h4>Carrera</h4>
                        <p><?php echo $_SESSION['identidad']->id_carrera;?></p>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>