<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Pinfbet</title>
        <link rel="stylesheet" href="Estatico/Estilos/estilos.css">
       
    </head>
    <body>
        <header>
            <div class = "barra_superior">
                <div class = "logo">
                     <a href="index.php"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>         
                </div>
                <nav class="navegacion">
                    <ul>
                        <li><a href= "index.php?c=Usuario&&a=contacto">Contacto</a></li>
                        <li><a href= "index.php?c=Usuario&&a=terminos">Condiciones</a></li>
                        <li><a href= "index.php?c=Usuario&&a=ayuda">Ayuda</a></li>
                    </ul>            
                </nav>
            </div>
        </header>

        <form class="form-register" method="POST" action="index.php?c=Usuario&&a=save">
            <h4>Formulario de Registro</h4>
            <input class="controls" type="text" name="nombres" id="nombres" placeholder="Ingrese su nombre"> 
            <input class="controls" type="text" name="apellidos" id="apellidos" placeholder="Ingrese su apellidos"> 
            <input class="controls" type="email" name="correos" id="correos" placeholder="Ingrese su correo"> 
            <input class="controls" type="password" name="contrasenas" id="contrasenas" placeholder="Ingrese su contraseña">
            <input class="controls" type="text" name="identificadores" id="identificadores" placeholder="Ingrese su usuario">
            <select class="controls" name="carreras" id="carreras">
                <option value="false">Seleccione una carrera:</option>
                <option value="GII">Ingeniería Informática</option>
                <option value="GIA">Ingeniería Aeroespacial</option>
                <option value="GIM">Ingeniería Mecánica</option>
            </select>
            <?php
                if (isset($_SESSION['error_registro']) && $_SESSION['error_registro']){
                    echo "<p class='error'>".$_SESSION['error_registro']."</p>";
                }
            ?>
            <p>Estoy de acuerdo con <a href="index.php?c=Usuario&&a=terminos">Términos y condiciones</a></p>
            <input class="botons" type="submit" name="register">
            <p><a href="index.php?c=Usuario&&a=iniciosesion">¿Ya tengo cuenta?</a></p>
        </form>

    </body>
</html>