<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="Estatico/Estilos/miperfil.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- cookiealert.css -->
    <link rel="stylesheet" href="Estatico/Estilos/cookiealert.css">
</head>
<body>
    <input type="checkbox" id="check">
    <header>
    
        <div class = "barra_superior">
            <div class = "logo">                
                 <a href="index.php?c=Usuario&&a=apuestas"><img src="Estatico/Imagenes/s2-minimized.png" alt="s2-minimized" ></a>  
                 <label for="check">
                    <i class="fas fa-bars" id="sidebar_btn" style="color:#707d8c;"></i>
                </label>      
            </div>
            <nav class="navegacion">
                <ul>
                    <li>
                        <div class="action" onclick="menuToggle();">
                            <div class="profile">
                                <img src="Estatico/Imagenes/avatar.png"  width="100%" height="100%">
                            </div>
                            <div class="menu">
                                <h3>
                                    <?php
                                         echo $_SESSION['identidad']->identificador;
                                    ?>
                                    <br><span>Diseñador Web</span>
                                </h3>
                                <ul>
                                    <li><img src="Estatico/Imagenes/user.png"><a href="index.php?c=Usuario&&a=miperfil">Mi perfil</a></li>
                                    <li><img src="Estatico/Imagenes/edit.png"><a href="index.php?c=Usuario&&a=editar_usuario">Editar perfil</a></li>
                                    <li><img src="Estatico/Imagenes/envelope.png"><a href="#">Bandeja</a></li>
                                    <li><img src="Estatico/Imagenes/log-out.png"><a href="index.php?c=Usuario&&a=logout">Cerrar Sesión</a></li>
                                </ul>
                            </div>
                        </div>
                        <script>
                            function menuToggle(){
                                const toggleMenu = document.querySelector('.menu');
                                toggleMenu.classList.toggle('active');
                            }
                        </script>
                    </li>
                </ul>            
            </nav>
        </div>
    </header>

    <div class="sidebar">
    <center>
            <?php
                $nombre_foto = $_SESSION['identidad']->id;
                $type = '.jpg';
                $nombre_foto = $nombre_foto.$type;                
                echo '<img src="Estatico/Profiles/'.$nombre_foto.'" class="profile_image" alt="">';
            ?>
           
            <h4>
                <?php
                    echo "Hola, ".$_SESSION['identidad']->identificador;
                ?>
            </h4>
        </center>
        <a href="index.php?c=Usuario&&a=apuestas"><i class="fas fa-home" style="color:#707d8c;"></i><span>Inicio</span></a>
        <a href="index.php?c=Usuario&&a=apostar"><i class="far fa-money-bill-alt" style="color:#707d8c;"></i><span>Apostar</span></a>
        <a href="index.php?c=Usuario&&a=amigos"><i class="fas fa-users" style="color:#707d8c;"></i><span>Amigos</span></a>
        <a href="index.php?c=Usuario&&a=aprobadas"><i class="far fa-thumbs-up" style="color:#707d8c;"></i><span>Asig.Aprobadas</span></a>
        <a href="index.php?c=Usuario&&a=asignaturas"><i class="far fa-address-book" style="color:#707d8c;"></i><span>Asig.Matriculadas</span></a>   
    </div>

    <div class="contenido">
        <div class="container">

            <!-- Primera Fila -->
            <div class="row ">

                    <!-- Columna Izquierda -->  
                    <div class="col-4">

                            <div class="card" style="width: 16rem;">
                            <?php
                                echo '<img src="Estatico/Profiles/'.$nombre_foto.'" class="card-img-top" alt="">';
                            ?>
                            <div class="card-body">
                                    <p class="card-text">Estudiante</p>
                                    <a href="#" class="btn btn-success">Enviar Solicitud</a>
                                </div>
                            </div>  

                    </div>
                        
                    <div class="col-6 align-self-center">


                            <div class="d-flex justify-content-md-center ">    
                                <div class="debit_card">
                                    <div class="card__front card__part">
                                        <img class="card__front-square card__square" src="https://image.ibb.co/cZeFjx/little_square.png">
                                        <img class="card__front-logo card__logo" src="Estatico/Imagenes/s2-minimized.png">
                                        <p class="card_numer">**** **** **** 6258</p>
                                        <div class="card__space-75">
                                        <span class="card__label">Card holder</span>
                                        <p class="card__info"><?php echo $_SESSION['identidad']->Nombre;?> <?php echo $_SESSION['identidad']->Apellidos;?></p>
                                        </div>
                                        <div class="card__space-25">
                                        <span class="card__label">Crédito</span>
                                                <p class="card__info"><?php echo $_SESSION['identidad']->pinfcoins;?></p>
                                        </div>
                                    </div>
                                    
                                    <div class="card__back card__part">
                                        <div class="card__black-line"></div>
                                        <div class="card__back-content">
                                        <div class="card__secret">
                                            <p class="card__secret--last">420</p>
                                        </div>
                                        <img class="card__back-square card__square" src="https://image.ibb.co/cZeFjx/little_square.png">
                                        <img class="card__back-logo card__logo" src="Estatico/Imagenes/s2-minimized.png">
                                        
                                        </div>
                                    </div>  
                                </div>
                            </div>


                    

                    </div>
            </div>
                 

            <br>

             
            <!-- Segunda Fila -->
            <div class="row">

                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class = "row no gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase">IDENTIFICADOR</div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800"><?php echo $_SESSION['identidad']->identificador;?></div>
                                    </div>
                                </div>    
                            </div>
                        </div>
                    </div>

                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class = "row no gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase">MI APELLIDO</div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800"><?php echo $_SESSION['identidad']->Apellidos;?></div>
                                    </div>
                                </div>    
                            </div>
                        </div>
                    </div>

                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class = "row no gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase">EMAIL</div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800"><?php echo $_SESSION['identidad']->email;?></div>
                                    </div>
                                </div>    
                            </div>
                        </div>
                    </div>


                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class = "row no gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase">MI GRADO</div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800"><?php echo $_SESSION['identidad']->id_carrera;?></div>
                                    </div>
                                </div>    
                            </div>
                        </div>
                    </div>
            </div>

        </div>
    </div>
 








</body>